# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 938bb6f4b94fbaf32aa67b17bb204b97e051c8bcb54613219374a59c7bf5da745b97466c727f63da0a2bfa1f12debbad88152de0b53f32f32dae28c97753be74

test:
  secret_key_base: e40ecd2e1faa1406fec6f300648b74c8cdbfd078e1694f860d68fda4ff6bb31a1adaa77995c7e6445819cf963232454e1536ab2aa6ba0bdca4aefc5cd7d49af1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
